name: non regression tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  
  build:
    runs-on: ubuntu-latest
    # container: ndesassis/test_ubuntu-16

    steps:
    - uses: actions/checkout@v2

    - name: Add python to path
      run : echo "/opt/python/py310/bin" >> $GITHUB_PATH

    - run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration (-j 16 option seems having no effect on Gitub Action)
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target build_tests -- -j 2

    - name: Install python wrapper
      # Install the python wrapper (not done automatically when running ctest)
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target python_install -- -j 2
      
    - name: Execute non-regression tests
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target check
