name: non regression tests under Windows (Visual)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Python dependency
      run: python -m pip install numpy

    - name: Configure cmake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Compile, install packages and execute non-regression tests
      # Execute tests defined by the CMake configuration.  
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target check
