name: non regression tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  
  build:
    runs-on: ubuntu-latest
    #container: ndesassis/test_ubuntu-16 # If restored, github workflow cannot change to myfibo/build directory !!!

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo apt-get install r-base

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Compile static and install python wrapper
      # Install the python wrapper (not done automatically when running make check)
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target python_install -- -j 2
      
    - name: Compile shared and execute non-regression tests
      # Execute tests defined by the CMake configuration.  
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target check
