name: publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  
  build:
    runs-on: ubuntu-latest
    container: ndesassis/test_ubuntu-16
    

    steps:
    - uses: actions/checkout@v2
    
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration (-j 16 option seems having no effect on Gitub Action)
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target build_tests -- -j 2

    - name: Test
      # working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ls ${{github.workspace}} & cd ${{github.workspace}} & ls & cd build & ls & ctest -C ${{env.BUILD_TYPE}} --output-on-failure
