name: publish_python_windows

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'     
        required: false
        default: ''  
env:
  BUILD_TYPE: Release
  BUILD_DIR : build
jobs:
   
  build:
    runs-on: windows-latest 
    steps:
    - uses: actions/checkout@v2
      
    - name : Create Wheels
      run : cmake -Bbuild -G "Visual Studio 17 2022"
   
    - name : install wheel
      run  : python3 -m pip install wheel

    - name : ls
      run : dir

    - name : Create Wheels
      run : cmake --build build --target python_install --config Release



    - name : wheel
      run : python3 build\python\Release\setup.py bdist_wheel
     

   

