name: publish_python_windows

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'     
        required: false
        default: ''  
env:
  BUILD_TYPE: Release
  BUILD_DIR : build
jobs:
   
  build:
    runs-on: windows-latest 
    steps:
    - uses: actions/checkout@v2
      
    - name : Create Wheels
      run : cmake -Bbuild -G "Visual Studio 17 2022"
   
    - name : install wheel
      run  : C:\hostedtoolcache\windows\Python\3.10.2\x64\python3.exe -m pip install wheel

    - name : Create Wheels
      run : cmake --build build --target python_install --config Release

    - run: |
        npm ci
        npm run build
        npm test

    - names : runs
      run : |
	cd build
        dir
        cd python
        dir
        cd Release
        dir 
        cd dist
        dir

#C:\hostedtoolcache\windows\Python\3.10.2\x64\python3.exe build\Repython3.exe setup.py bdist_wheel
     

   

