name: publish_python_windows_boost

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'     
        required: false
        default: ''  
env:
  BUILD_TYPE: Release
  BUILD_DIR : build
  BOOST_ROOT: ${{github.workspace}}\3rdparty\boost
  BOOST_URL: https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.bz2/download

jobs:
   
  build:
    runs-on: windows-latest 
    steps:
    - uses: actions/checkout@v2
    
    - run: |
        mkdir -p $BOOST_ROOT
        curl --progress-bar --location --output $BOOST_ROOT/download.tar.bz2 $BOOST_URL
        7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar.bz2 -y -bd
        7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar -y -bd
        cd $BOOST_ROOT && cp -r boost_*/* .
        rm -rf boost_*/* download.tar.bz2 download.tar

    - name : Create Wheels
      run : cmake -B$${{env.BUILD_DIR}} -G "Visual Studio 17 2022"
   
    - name : install wheel
      run  : C:\hostedtoolcache\windows\Python\3.10.2\x64\python3.exe -m pip install wheel

    - name : Create Wheels
      run : cmake --build $${{env.BUILD_DIR}} --target python_install --config Release

    - run: |
        C:\hostedtoolcache\windows\Python\3.10.2\x64\python3.exe -m pip install twine 
        cd $${{env.BUILD_DIR}}\python\${{env.BUILD_TYPE}}
        C:\hostedtoolcache\windows\Python\3.10.2\x64\python3.exe setup.py bdist_wheel
        C:\hostedtoolcache\windows\Python\3.10.2\x64\python3.exe -m twine upload dist\*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
        TWINE_REPOSITORY: testpypi
       # BOOST_ROOT: ${{github.workspace}}\3rdparty\boost
      #BOOST_URL: https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.bz2/download
     

   

