name: publish_python_windows

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'     
        required: false
        default: ''  
env:
  BUILD_TYPE: Release
  BUILD_DIR : build
  DOXYGEN_ROOT : Doxygen
  DOXYGEN_URL : https://www.doxygen.nl/files/doxygen-1.9.3.windows.x64.bin.zip
  COMPILE_VERSION : '"Visual Studio 17 2022"' #Because cmake -G needs " "
  PYTHON3_PREF : C:\hostedtoolcache\windows\Python
  PYTHON3_SUFF : x64

jobs:
   
  build:
    runs-on: windows-latest 
    strategy :
      matrix:
       python: 
        # - ["cp310-cp310","3.10.2"]
          - ["cp39-cp39","3.9.10"]
          - ["cp38-cp38","3.8.12"]
        # - ["cp37-cp37m","3.7.12"]
    
    steps:
    - uses: actions/checkout@v2

    - name : Setup variables
      run : |
       echo "$PYTHONPATH=${{env.PYTHON3_PREF}}\${{matrix.python}}[1]\${{env.PYTHON_SUFF}}">> $GITHUB_ENV
       echo "$PYTHON3=${{env.PYTHONPATH}}\python3.exe" >> $GITHUB_ENV
 
    - name : Modify PATH
      run : echo "$PYTHONPATH" >> $GITHUB_PATH

    - name : print
      run : |
       echo $PYTHONPATH
       echo ${PYTHONPATH}
       echo ${{PYTHONPATH}}
     
    - name : Download and install Doxygen  
      run: |
        mkdir ${{env.DOXYGEN_ROOT}}
        cd ${{env.DOXYGEN_ROOT}}
        mkdir bin
        cd .. 
        curl --progress-bar --output ${{env.DOXYGEN_ROOT}}/download.zip ${{env.DOXYGEN_URL}}
        7z -o${{env.DOXYGEN_ROOT}}/bin x ${{env.DOXYGEN_ROOT}}/download.zip 

    - name : Configure Cmake
      run : |
       cmake -B${{env.BUILD_DIR}} -G ${{env.COMPILE_VERSION}} -DDoxygen_ROOT=${{env.DOXYGEN_ROOT}} 

    - name : Install wheel and twine
      run: |
       $PYTHON3 -m pip install wheel
       $PYTHON3 -m pip install twine 

    - name : Library compilation
      run : cmake --build ${{env.BUILD_DIR}} --target python_install --config Release
 
    - name : Build and upload wheel
      run: |
        cd ${{env.BUILD_DIR}}\python\${{env.BUILD_TYPE}}
        $PYTHON3 setup.py bdist_wheel
        $PYTHON3 -m twine upload dist\*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
        TWINE_REPOSITORY: testpypi



   


   

