name: publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  BUILD_DIR : build
jobs:
   
  build:
    runs-on: ubuntu-latest
    strategy :
      matrix:
       python: ["cp38","cp39"]
    container:
      image: ndesassis/testrepo
 
    steps:
   
    - uses: actions/checkout@v2
      
    - name : Create Wheels
      run : deploy/pythonBuild.sh  ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}} ${{matrix.python}}
      
    - name : Install twine
      run : python3.10 -m pip install twine 

    - name : Upload
      run : python3.10 -m twine upload ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}}/dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
        TWINE_REPOSITORY: testpypi

   

