name: publish_python_macos

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'     
        required: false
        default: ''  
env:
  BUILD_TYPE: Release
  BUILD_DIR : build
  PYTHON3 : python3

jobs:
   
  build:
    runs-on: macos-11 
    steps:
    - uses: actions/checkout@v2

    - name : Download and install Doxygen  
      run: brew install doxygen

    - name : Configure Cmake
      run : |
       cmake -B${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=Release
#-DDoxygen_ROOT=${{env.DOXYGEN_ROOT}} 

    - name : Install wheel and twine
      run: |
       ${{env.PYTHON3}} -m pip install wheel
       ${{env.PYTHON3}} -m pip install twine 

    - name : Library compilation
      run : cmake --build ${{env.BUILD_DIR}} --target python_install --config Release
 
    #- name : Build and upload wheel
    #  run: |
    #    cd ${{env.BUILD_DIR}}\python\${{env.BUILD_TYPE}}
    #    ${{env.PYTHON3}} setup.py bdist_wheel
    #    ${{env.PYTHON3}} -m twine upload dist\*
    #  env:
    #    TWINE_USERNAME: __token__
    #    TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
    #    TWINE_REPOSITORY: testpypi



   


   

